export const env = {
  BASEMULTI_KEY: process.env.BASEMULTI_KEY,
  DB_DRIVER: process.env.DB_DRIVER,
  DB_HOST: process.env.DB_HOST,
  DB_PORT: process.env.DB_PORT,
  DB_USERNAME: process.env.DB_USERNAME,
  DB_PASSWORD: process.env.DB_PASSWORD,
  DB_DATABASE: process.env.DB_DATABASE,
  NEXT_PUBLIC_URL: process.env.NEXT_PUBLIC_URL,
  NEXT_PUBLIC_DISABLE_PROVIDERS: process.env.NEXT_PUBLIC_DISABLE_PROVIDERS,
  AWS_ENDPOINT: process.env.AWS_ENDPOINT,
  AWS_REGION: process.env.AWS_REGION,
  AWS_AK: process.env.AWS_AK,
  AWS_SK: process.env.AWS_SK,
  AWS_BUCKET: process.env.AWS_BUCKET,
  AWS_BUCKET_URL: process.env.AWS_BUCKET_URL,
  AWS_DIRECTORY: process.env.AWS_DIRECTORY,
  ADMIN_EMAIL: process.env.ADMIN_EMAIL,
};